name: Build Tesseract-Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      if: matrix.os != 'windows-latest'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y gcc make
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install gcc make
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install mingw make
    - name: Build Tesseract-Debug
      run: make tesseract-debug
    - name: Determine Binary Name
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          echo "BINARY_NAME=tesseract-debug.exe" >> $GITHUB_ENV
        else
          echo "BINARY_NAME=tesseract-debug" >> $GITHUB_ENV
        fi
    - name: Upload Tesseract-Debug Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tesseract-debug-${{ matrix.os }}
        path: ${{ env.BINARY_NAME }}
